Week-2-Bandit_Labs
MLuka1/luka-mirnic-devops-mentorship pull request #2
Opened 2023-02-27 15:40 UTC by MLuka1

Creating a pull request for week-2 task. Following actions have been made.

1. Created new branch called week-2-bandit-labs from branch main.
2. Created week-2 folder and file bash.notes.md inside local luka-mirnic-devops-mentorship repository.
3. Successfully completed tasks on bandit labs up to Level 10 and made screenshots for confirmation.
4. Explained every command that has been used during the process inside bash.notes.md file.
5. Added, committed and pushed changes through Git Bash from local to remote repository.

2023-02-27 17:08 UTC, borisbradic requested changes
You are missing 'bandit10'.

2023-02-28 00:40 UTC, MLuka1 commented
> You are missing 'bandit10'.

Added bandit10.

2023-02-28 09:11 UTC, borisbradic approved these changes

2023-02-28 09:12 UTC, borisbradic commented
All good now!

2023-02-28 09:12 UTC, merged